template_experiment_config with __init__ and evalutate_genomes functions
EvolvingNN/pytorch-neat pull request #8
Opened 2022-10-28 20:06 UTC by aidanhor-n

2022-10-28 23:05 UTC, GregoryConrad requested changes

2022-10-28 23:05 UTC, GregoryConrad commented on neat/experiments/template/config.py
> +        self.PERCENTAGE_TO_SAVE = kwargs['PERCENTAGE_TO_SAVE']
assuming you are given a dict of all the parameters in kwargs, something like the following would be a great simplification of this:
```python3
for k, v in kwargs.items():
  setattr(self, k, v)
```
This is also not error-prone to a typo in a string or forgetting items.

2022-10-28 23:05 UTC, GregoryConrad commented on neat/experiments/template/config.py
> +    def eval_genomes(self, genomes):
NOTE: I have not reviewed this particular method yet b/c of the lot of TODOs. Please clean up the other areas I mentioned and complete those TODOs and then I will take a look at this method

2022-10-29 19:38 UTC, GregoryConrad requested changes
Please undo the changes to /images/pole-balancing-solution and move the pole_run file back to it's original place

2022-10-29 19:38 UTC, GregoryConrad commented on images/pole-balancing-solution
>  	node [fontsize=9 height=0.2 shape=circle width=0.2]
This file is still not the same as the one on master; please revert

2022-10-29 19:42 UTC, GregoryConrad requested changes

2022-10-29 19:42 UTC, GregoryConrad commented on neat/experiments/template/default_kwarg
> +default_kwarg = {
Also, please change the file extension to .py

2022-10-29 19:42 UTC, GregoryConrad commented on neat/experiments/template/config.py
> +        self.PERCENTAGE_TO_SAVE = kwargs['PERCENTAGE_TO_SAVE']
Please change __init__ to use this.

2022-10-29 19:42 UTC, GregoryConrad commented on neat/experiments/template/config.py
> +    def __init__(self, **kwargs):
how is kwargs going to be used?

2022-10-31 14:50 UTC, aidanhor-n commented on neat/experiments/template/config.py
> +    def __init__(self, **kwargs):
yes, the plan is to deep copy DEFAULT_KWARGS and change it for experiment specific parameters.

2022-11-01 16:39 UTC, GregoryConrad approved these changes

2022-11-01 16:39 UTC, merged